category: Web
description: Blunt converts between pointfree and pointful expressions.
executables:
  blunt:
    dependencies:
    - base
    - blunt
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: tfausak/blunt
library:
  dependencies:
  - aeson
  - autoexporter
  - base
  - bytestring
  - clay
  - ekg
  - envy
  - hslogger
  - http-types
  - jmacro
  - lucid
  - newtype-generics
  - pointfree
  - pointful
  - signal
  - text
  - wai
  - wai-websockets
  - warp
  - websockets
  - wl-pprint-text
  other-modules: Paths_blunt
  source-dirs: library
license: MIT
maintainer: Taylor Fausak
name: blunt
synopsis: Convert between pointfree and pointful expressions.
version: '2.0.0'
