category: Web
description: Blunt is a web front end to the pointfree and pointful libraries.
executables:
  blunt:
    dependencies:
    - base
    - blunt
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options:
- -Wall
github: tfausak/blunt
library:
  dependencies:
  - base ==4.*
  - aeson >=0.8 && <0.12
  - bytestring ==0.10.*
  - clay ==0.10.*
  - flow ==1.*
  - http-types >=0.8 && <0.10
  - jmacro ==0.6.*
  - lucid ==2.*
  - pointfree >=1.1 && <2
  - pointful >=1.0.6 && <2
  - text ==1.*
  - wai ==3.*
  - wai-extra ==3.*
  - wai-websockets ==3.*
  - warp ==3.*
  - websockets ==0.9.*
  - wl-pprint-text ==1.*
  source-dirs: library
license: MIT
maintainer: Taylor Fausak
name: blunt
synopsis: Automatically re-export modules.
version: '1.0.2'
